### ISSUE TITLE
Show signature automatically

### ISSUE THREAD

**Issue by iamntz** [predragnikolic/SIDE#2]
First of all: **awesome** plugin! I'm using it for 5 mins and already love it. Great job!

Here is an idea: a function signature should be displayed all the time when you're editing a function parameters (i.e. not only on bracket opening but also on typing).

**Comment by predragnikolic** [comment]
First of all, **thanks**. Really glad you liked it :)

I thought about that idea, but here is what I realized.

Imagine that you have a file, with two `run` definitions in the same file, with different signatures.
When there are multiple definitions of the same symbol in the current file or the opened files, 
SIDE will show you an overload, you can use `up`,`down` arrows to go through the suggestions and if you press `enter` and the caret is not right next to the opening bracket, it will take you to that definition.

![2019-01-23-231131_653x354_scrot](https://user-images.githubusercontent.com/22029477/51640640-597bff80-1f64-11e9-8a6c-9afa75e10604.png)

As you can see, SIDE is not showing you the right signature.
[1-2] this means that it is showing the 1 signature out of 2.
And if I were to implement signature so it displays all the time on typing,
Than it would constantly show you the wrong signature in this case, 
And that would be annoying. 

So I don't see it happening for now :)
